# Generated by Django 4.1.7 on 2023-02-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RemoveField(
            model_name='autor',
            name='description',
        ),
    ]
