# Generated by Django 4.1.7 on 2023-02-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0004_alter_libro_autor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraLiteraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField()),
                ('autores', models.ManyToManyField(to='Libreria.autor')),
            ],
        ),
    ]
