# Generated by Django 4.1.7 on 2023-02-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0005_obraliteraria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obraliteraria',
            options={'ordering': ['titulo'], 'verbose_name': 'Obra Literaria', 'verbose_name_plural': 'Obras Literarias'},
        ),
    ]
