# Generated by Django 4.1.7 on 2023-02-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0006_alter_obraliteraria_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='nacionaliad',
            new_name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
