# Generated by Django 4.1.7 on 2023-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0007_rename_nacionaliad_autor_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='apodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
