# Generated by Django 4.1.7 on 2023-02-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0009_autor_fecha_creacion_alter_autor_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='Soon', max_length=1300, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='obraliteraria',
            name='descripcion',
            field=models.TextField(default='Soon', max_length=1300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='obraliteraria',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
