# Generated by Django 4.1.7 on 2023-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0010_autor_correo_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_id',
            new_name='autor',
        ),
        migrations.AlterField(
            model_name='libro',
            name='descripcion',
            field=models.TextField(default='', max_length=1300, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='obraliteraria',
            name='descripcion',
            field=models.TextField(default='', max_length=1300, verbose_name='Descripcion'),
        ),
    ]
